language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm
 
matrix:
  allow_failures:
    - php: hhvm

before_install:
  ## Packages
  - sudo apt-get -qq update

efore_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source
  ## PHPDocumentor
  - mkdir -p build/docs
  - mkdir -p build/coverage

script:
  ## PHP_CodeSniffer
  - ./vendor/bin/phpcs src/ tests/ --standard=PSR2 -n
  ## PHP Copy/Paste Detector
  # - ./vendor/bin/phpcpd src/
  ## PHP Mess Detector
  - ./vendor/bin/phpmd src/,tests/ text ./phpmd.xml.dist
  ## PHPUnit
  - ./vendor/bin/phpunit -c ./ --coverage-text --coverage-html ./build/coverage
  ## PHPLOC
  - ./vendor/bin/phploc src/
  ## PHPDocumentor
  - ./vendor/bin/phpdoc -q -d ./src -t ./build/docs --template="responsive-twig"

notifications:
  email: false
