language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm
 
matrix:
  allow_failures:
    - php: hhvm

before_script:
  ## Packages
  - sudo apt-get -qq update > /dev/null
  ## Composer
  - composer self-update
  - composer install --prefer-source --dev
  - composer install --no-interaction
  - phpenv global "$TRAVIS_PHP_VERSION"
  ## Codesniffer
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  ## PHP_CodeSniffer
  - phpcs --report-width=200 --report-summary  --report-full Classes/ unitTests/ --standard=PSR2 -n
  ## PHPUnit
  - phpunit -c ./unitTests/

notifications:
  email: false
